# Generated by Django 3.0.7 on 2021-01-29 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20210129_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='flavor',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='size',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='customitem',
            name='name_on_cake',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='NameOnCake',
        ),
    ]
