# Generated by Django 3.0.7 on 2021-01-29 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20210129_1216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='customitem',
            name='status',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='customitem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.CustomItem'),
        ),
    ]
