# Generated by Django 3.0.7 on 2021-01-29 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20210129_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='customitem',
        ),
        migrations.AddField(
            model_name='customitem',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Order'),
        ),
        migrations.AddField(
            model_name='customitem',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Out for delivery', 'Out for delivery'), ('Delivered', 'Delivered')], max_length=200, null=True),
        ),
    ]
