# Generated by Django 3.0.7 on 2021-01-29 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20210129_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='customitem',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
