# Generated by Django 3.0.7 on 2021-01-29 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_customitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='customitem',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Seller'),
        ),
    ]
