# Generated by Django 3.0.7 on 2021-01-29 18:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_customitem_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customitem',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
